### ISSUE TITLE
Feature Request: 'PUNCTUATION SPACE' (U+2008)

### ISSUE THREAD

**Issue by jeroen-mostert** [microsoft/cascadia-code#230] opened 2020-01-13 13:48 UTC
# Description of the new feature/enhancement (with images if possible)

My custom regional settings use U+2008 PUNCTUATION SPACE as the thousands separator in numbers. Consolas and Fira Code display this as a regular space, so Cascadia displaying a replacement character in directory listings is very visible.

If a bit of scope creep is permitted, rather than patiently gathering individual requests for all the [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character), it may be worth just adding all the horizontal ones at once (mapping them to a regular space), as in "might not be correct spacing, but the best we can do in monospace, and certainly no worse than a replacement character".

**Comment by ExE-Boss** [comment] 2020-01-14 12:34
Well&nbsp;`U+3000` should&nbsp;still cover&nbsp;two&nbsp;cells, as&nbsp;it’s&nbsp;a&nbsp;fullwidth CJK&nbsp;space.

**Comment by aaronbell** [comment] 2020-03-09 16:36
I'm guessing that we would end up needing to make a custom version of Cascadia to support CJK (due to full width / halfwidth support). So uni2008 would probably just be a duplicate of the normal space character in this font, at least. 

Definitely worth considering adding all of the whitespace characters at once! Thanks.

**Closed** 2020-05-01 17:32 UTC
Labels: Issue-Feature
