### ISSUE TITLE
List of ligature combinations Documentation Issue

### ISSUE THREAD

**Issue by ArjangAssadi** [microsoft/cascadia-code#86] opened 2019-09-20 21:42 UTC
Is there a list of characters combinations and their corresponding ligatures?

**Comment by DHowett-MSFT** [comment] 2019-09-20 21:43
duplicate of #37 -- **please search before reporting a new issue**

**Closed by DHowett-MSFT** 2019-09-20 21:43 UTC

**Comment by ArjangAssadi** [comment] 2019-09-20 23:04
The list is not in documentation, this is still a documentation issue,

**Comment by DHowett-MSFT** [comment] 2019-09-20 23:09
That documentation issue is already covered by #37.
