### ISSUE TITLE
Ligatures rendering issues on windows/vscode low dpi

### ISSUE THREAD

**Issue by Eldair** [microsoft/cascadia-code#267] opened 2020-05-14 09:03 UTC
# Environment

```none
Cascadia Code version number: 2004.300 (bundled with terminal)
Application (with version) used to display text: vscode insiders 1.46
OS platform and version: Windows 10 19041.264
Screen resolution (i.e. 220dpi): 96dpi
```

# Expected behavior

Proper line thickness and spacing

# Actual behavior

15px (first line on first two ligs):
![image](https://user-images.githubusercontent.com/470003/81915174-88dbd300-95d2-11ea-8e0b-55eb93c8fe07.png)
14px (second ligature last line):
![image](https://user-images.githubusercontent.com/470003/81914917-34385800-95d2-11ea-97cf-a9bcd38c360e.png)
13px (everything is weird):
![image](https://user-images.githubusercontent.com/470003/81915033-56ca7100-95d2-11ea-81a1-2d69b6eebec2.png)
12px (this looks ok):
![image](https://user-images.githubusercontent.com/470003/81915088-6a75d780-95d2-11ea-8c85-d68ef7204624.png)

**Comment by Taomyn** [comment] 2020-05-14 10:21
I'm seeing some very strange issues with the latest version, this is just in Notepad++, both on Windows Servers 2016, albeit different machines/dpi, but it was fine before I updated the font - yes I removed the old one first, and have also rebooted.

Now:
![image](https://user-images.githubusercontent.com/4365929/81922820-f68cfc80-95dc-11ea-9673-daccb3c3cae7.png)

Before:
![image](https://user-images.githubusercontent.com/4365929/81922836-fa208380-95dc-11ea-91f5-b9f825c7fe50.png)


Happens with all four TTF font versions

**Comment by aaronbell** [comment] 2020-05-14 13:33
@Taomyn can you open this as a separate bug? Thanks!

**Comment by Taomyn** [comment] 2020-05-14 16:59
> @Taomyn can you open this as a separate bug? Thanks!

Done https://github.com/microsoft/cascadia-code/issues/269#issue-618393500

**Comment by aaronbell** [comment] 2020-05-14 20:20
Thanks for this bug! It looks like this is a dupe of #249, which we are still deciding how best to address. Closing for now.

**Closed by aaronbell** 2020-05-14 20:20 UTC
