### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by Ajmdag** [microsoft/cascadia-code#95] opened 2019-09-21 15:06 UTC
# Description of the new feature/enhancement (with image)
I installed this font and set it in VSCode.
It seems like Cyrillic symbols are not supported.
Could you implement this feature?

![](https://i.imgur.com/j1m8jAJ.png)

Programmers who have Cyrillic symbols in their code will be happy using this wonderful font.

**Comment by AliveDD** [comment] 2019-09-23 11:40
amazing font, looks great in VScode, more expressive than Monaco
but need CYR, yeah, than i'll change :)

**Comment by cinnamon-msft** [comment] 2019-09-24 17:53
Duplicate of #33

**Closed by cinnamon-msft** 2019-09-24 17:53 UTC
Labels: Issue-Feature
