### ISSUE TITLE
Special characters don't behave as monospace

### ISSUE THREAD

**Issue by estebanglas** [microsoft/cascadia-code#54] opened 2019-09-19 11:56 UTC
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: Windows Notepad
OS platform and version: Windows 10 64bi Pro 1903 build 18975 (Insider Preview) and 18362
Screen resolution (i.e. 220dpi): 

Any text editors to be honest
```

# Steps to reproduce

Use any Spanish special characters (and I assume any other language's special characters) 

áéíóú ÁÉÍÓÚ üÚ ñÑ

# Expected behavior
Font should behave as monospace (same width for every character) This does not happen with special characters 

# Actual behavior

Character width is smaller than expected. 

![image](https://user-images.githubusercontent.com/3653865/65241914-29690a00-dabb-11e9-8661-5ed5b568c2cf.png)

# Note
Probably related to: #52 and #49

**Comment by estebanglas** [comment] 2019-09-19 12:04
Same behaviour on the new Windows Terminal: 
![image](https://user-images.githubusercontent.com/3653865/65242449-65e93580-dabc-11e9-93f3-26647a6ad3ae.png)

**Comment by jroessel** [comment] 2019-09-19 13:40
Those characters are not part of the font and thus subject to font substitution. So the glyphs you see come from a different font, with (predictably) different metrics.

**Comment by estebanglas** [comment] 2019-09-19 14:03
Makes sense, thus maybe change it to "Feature Request" rather than "Bug" ?

**Comment by jroessel** [comment] 2019-09-19 14:03
That request seems to exist in #33.

**Comment by cinnamon-msft** [comment] 2019-09-19 22:03
This is a duplicate of #33

**Closed by cinnamon-msft** 2019-09-19 22:03 UTC
