### ISSUE TITLE
Support Vietnamese characters

### ISSUE THREAD

**Issue by quannh25595** [microsoft/cascadia-code#106] opened 2019-09-23 09:38 UTC
Please support these character
á à ả ã ạ ă ắ ằ ẵ ẳ ặ â ấ ầ ẫ ẩ ậ ú ù ũ ủ ụ ư ứ ừ ữ ử ự ó ò õ ỏ ọ ô ố ồ ỗ ổ ộ ơ ớ ờ ỡ ở ợ

It's not usually used in code. But sometimes we still need this in string or html

**Comment by cinnamon-msft** [comment] 2019-09-25 19:53
Duplicate of #33

**Closed by cinnamon-msft** 2019-09-25 19:53 UTC
Labels: Issue-Feature
