### ISSUE TITLE
Bug Report: a non-monospaced fixed-width font?

### ISSUE THREAD

**Issue by LinkeyLeo** [microsoft/cascadia-code#243] opened 2020-03-05 15:14 UTC
# Environment

Cascadia Code version number: 1911.210
Application (with version) used to display text: Visual Studio 2019 16.5.0 Preview 5
OS platform and version: Windows 10 19569
Screen resolution (i.e. 220dpi): without dpi scaling applied

# Steps to reproduce

theme set to dark (i don't think this matters)
editor font set to Cascadia Code (also tried Cascadia Mono, same problem)
editor font size set to 16 (also tried 10, 12, 14, same problem)
tried disable all extension, nothing changes

![image](https://user-images.githubusercontent.com/10334184/75994795-755b1e80-5f36-11ea-8158-a539f7345b31.png)

it obviously not aligned

**Comment by LinkeyLeo** [comment] 2020-03-05 15:17
this seems to be bold type has different width with regular type

**Comment by aaronbell** [comment] 2020-03-09 15:52
At current the font does not include a bold weight (see #128 ). As such, when you embolden the glyphs, it is being done programmatically, and incorrectly, thus resulting in a different width than standard Cascadia Code. Once a bold weight is added, this will no longer be an issue. 

Closing as a dupe of #128.

**Closed by aaronbell** 2020-03-09 15:52 UTC
