### ISSUE TITLE
Setting editor.fontWeight to 300 in VSCode makes all text italic

### ISSUE THREAD

**Issue by smlombardi** [microsoft/cascadia-code#531] opened 2021-07-13 19:38 UTC
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

MacOS 11.4

### Other Software

Visual Studio Code

### What happened?

I used to use the static fonts but followed the suggestion in the ReadMe that the TTF has better hinting and should be used.

Checking in Font Book shows a lot of weights:

![User-20210713_152615](https://user-images.githubusercontent.com/835148/125513357-7d54eaad-0b82-4fa9-8246-463780be7c22.png)

I'd like to use a lighter weight in VS Code, but if I set it to 300, the font is all italic:

![~LibraryApplication SupportCode - InsidersUsersettings json — ng-designsystem-20210713_152933](https://user-images.githubusercontent.com/835148/125513745-9179b941-a68d-49f1-84bc-88e68daa40c9.png)

It seems to work as expected in Terminal where I can use a GUI to set the weight:

![Profiles-20210713_153350](https://user-images.githubusercontent.com/835148/125514120-f0734039-f241-4fdd-a0e2-550bd78b74a4.png)

as you can see, it looks like Light here:

![ttf — st016lo@US-ST016LO-MLT —  e-2106 17ttf — -zsh-20210713_153739](https://user-images.githubusercontent.com/835148/125514530-4a04b567-fa75-4585-8059-33d49fa1b980.png)

**Comment by aaronbell** [comment] 2021-07-13 19:44
Hm. I'm not seeing that issue in VS Code myself. It may be caused by multiple font installs causing issues. I would suggest uninstalling all versions of the fonts, restarting, and reinstalling.

**Comment by smlombardi** [comment] 2021-07-13 19:57
I did, more than once.  If I install the static OTF fonts, then I can set the font to "Cascadia Code Light"

![Settings — ng-designsystem-20210713_155731](https://user-images.githubusercontent.com/835148/125516801-5765e238-8af6-4512-8133-dd376685286d.png)

**Comment by aaronbell** [comment] 2021-07-13 21:15
Hm. I'm afraid I'm not sure what's going on for you! Given that you're on a mac, just go ahead and use the OTFs. :)

**Comment by aaronbell** [comment] 2021-07-14 01:43
It looks like this is the same issue as #500, so I'll close this and continue discussion over there.

**Closed by aaronbell** 2021-07-14 01:43 UTC

**Comment by aaronbell** [comment] 2021-07-14 01:49
BTW, out of interest, can you provide a bit more information about the system / VS Code version that you're using? I feel like this is likely a platform-specific issue but want to make sure.

**Comment by smlombardi** [comment] 2021-07-14 11:16
Mac OS 11.4

Version: 1.59.0-insider
Commit: 807dfb817fef0d0c5729c1924bd4889b04fa405b
Date: 2021-07-13T09:15:26.467Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
