### ISSUE TITLE
Cascadia Code suddenly stopped showing up as a valid font in console windows (not Windows Terminal)

### ISSUE THREAD

**Issue by nathan-alden-hp** [microsoft/cascadia-code#594] opened 2021-10-28 19:25 UTC
### Cascadia family version

2108.026

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

I don't know

### Platform

Windows 10 1809

### Other Software

PowerShell Core 7.1.5

### What happened?

I have a machine running Windows 10 1809. Just today I ran Windows Update, uninstalled Visual Studio 2019, and installed Visual Studio 2022 RC. After doing all this, I noticed my PowerShell Core terminal window started showing up in italics:

![image](https://user-images.githubusercontent.com/40613229/139321748-4b45eff9-21b3-43a0-903c-9422503b1132.png)

When I inspected the font configuration, I noticed that `Cascadia Code` is no longer listed; instead, the window appears to be defaulting back to `Raster Fonts`, even though the actual font the window is rendering appears to be `Cascadia Code` italics.

![image](https://user-images.githubusercontent.com/40613229/139321893-5f2b691b-0de1-4a9e-bd84-da625636ceb5.png)

Note that Cascadia Code is no longer available for selection:

![image](https://user-images.githubusercontent.com/40613229/139322151-ffca6f7c-2a97-43d6-82cb-0a5286714e7d.png)

I then inspected the font in Windows' Fonts control panel:

![image](https://user-images.githubusercontent.com/40613229/139321968-3e0aa8ea-d5d9-4de5-8f10-25ca01831424.png)

It looks like somehow the non-italic typefaces became uninstalled, so PowerShell Core is selecting the next available typeface.

This may be related to https://github.com/microsoft/cascadia-code/issues/591.

**Comment by aaronbell** [comment] 2021-10-29 19:13
I do seem to recall folks having issues with Windows updates when they'd installed the font within the user scope rather than system-wide, but that doesn't necessarily seem to tell the whole story here as the PL versions are OK. 

@DHowett, it seems strange that this would be happening with Cascadia Mono and Cascadia Code. Might this be due to that they are being installed/managed by Windows Terminal versus manual install (as the PL versions would be)?

**Comment by DHowett** [comment] 2021-10-29 19:15
This is almost certainly the same issue that's been plaguing Terminal since Version like 0.5. It's terrifically frustrating.

"Repairing" the Terminal application in "All apps and features" should fix this, as should rebooting (?)

**Comment by aaronbell** [comment] 2021-10-29 19:36
Thanks Dustin. It seems like this is not an issue with the font itself but with Windows Terminal, so I’ll go ahead and close it on this end.

**Closed by aaronbell** 2021-10-29 19:36 UTC

**Comment by ChameleonDevil** [comment] 2021-11-02 07:30
> Thanks Dustin. It seems like this is not an issue with the font itself but with Windows Terminal, so I’ll go ahead and close it on this end.

How exactly do you get to that conclusion that it 'not an issue with a font itself', but with Windows Terminal, seemingly completely ignoring my post above (as others also pointed out above me), where I confirmed that Terminal/Windows Terminal/ **and VS Code** does not have access to Cascadia fonts anymore since last week.

See my comment above:
https://github.com/microsoft/cascadia-code/issues/594#issuecomment-954565361

Sure, this may not be 'directly' be an issue with the font, but **something is causing Windows to refuse to install/reinstall fonts that used to be there : namely `Cascadia Mono`, `Cascadia Code`, but now aren't available no matter what I tried.** 
The only fonts **installable** are `Cascadia Mono PL` and `Cascadia Code PL` versions.

I hope this points you in the right direction to realise perhaps the non-PL versions do not work, for whatever reason, **and some software (Terminal/Windows Terminal) use the non-PL version by default!**

**Comment by aaronbell** [comment] 2021-11-02 12:48
Windows Terminal currently ships with Cascadia Code and Cascadia Mono, installing the two fonts via some back-channel method that isn’t really ‘officially’ installing them. These versions are the only ones that Windows Terminal will use.

For fun, you can download and install the fonts manually, even if you have Windows Terminal already present. All other applications on the system will be able to access and use the manually installed versions but Windows Terminal will still try to use the ones it shipped with.

So this issue is related to how Windows Terminal is “installing” the fonts onto the system that renders them inaccessible rather than the font files themselves that are failing.

As such, the problem should be filed / discussed on the Windows Terminal repository.

**Comment by ChameleonDevil** [comment] 2021-11-02 13:19
Ok thanks for the explanation, however : 

> For fun, you can download and **install the fonts manually**, even if you have Windows Terminal already present. All other applications on the system will be able to access and use the manually installed versions but Windows Terminal will still try to use the ones it shipped with.

So using this as I tried (according to installation pages):
_Should be able to install versions **manually** (or via ZIP) and non-PL versions should also work? _
````
choco install cascadiacode
choco install cascadiamono
choco install cascadiacodepl
choco install cascadiamonopl
````

As a minimum I would have expected the non-PL versions to then **be manually installed**, which as I explained last week doesn't happen, so Windows Terminal's installation method prevents these 'manual installation methods' from actually working? And whilst I used VS Code with `Cascadia Mono`, I always used this 'Windows Terminal font installation' which then broke down last week.

There is absolutely no way that any manual method gets those versions reinstalled currently; so I do not know if any of this is useful or not.

**Comment by aaronbell** [comment] 2021-11-02 13:40
As I said, even if you manually install the font, Windows Terminal will always use its custom install (I had fun discovering this while working on the font and not seeing changes I made reflected in WT). I don’t know about Visual Studio’s implementation.

AFAIK, the only solution (as @Dhowett posted above), is 
> "Repairing" the Terminal application in "All apps and features" should fix this, as should rebooting (?)
