### ISSUE TITLE
[Feature Request] International Characters/Glyphs

### ISSUE THREAD

**Issue by angelhdz** [microsoft/cascadia-code#124] opened 2019-09-26 18:11 UTC
# Description of the new feature/enhancement (with images if possible)

**Feature Request:** Add international glyphs. For exampled, my main language is Spanish so I tried writing my name containing an á ('a' with accute/accent) and it's printed with another default font.  Or if there were an easy way that I could add those glyphs myself, please tell.
![image](https://user-images.githubusercontent.com/10191085/65712573-55f5c680-e065-11e9-9da1-06d69806d1b8.png)

Thank you? 🤔

# Proposed technical implementation details (optional)

**Comment by aaronbell** [comment] 2019-09-27 17:50
Duplicate of #33

**Closed by aaronbell** 2019-09-27 17:50 UTC
Labels: Issue-Feature
