### ISSUE TITLE
incorrect glyph of lower case letter 'x' in a hexadecimal number

### ISSUE THREAD

**Issue by xenalipin** [microsoft/cascadia-code#303] opened 2020-06-29 06:31 UTC
# Environment

```
Cascadia Code version number: Cascadia Mono 2005.150
Application (with version) used to display text: Visual Studio 2017 & 2019
OS platform and version: Windows 10 1809 Enterprise LTSC
Screen resolution (i.e. 220dpi): 96dpi
```

# Steps to reproduce

I use `Cascadia Mono` rather than `Cascadia Code` for times since that I do not like any fonts with ligatures. I found a problem (I am not sure whether it is a problem) about `Cascadia Mono` recently.

The lower case letter `x` in code editor of Visual Studio is displayed normally. But, it is displayed like a `×` (a multiplication sign) only if it is a part of a hexadecimal number, like `0x00000001`, while the upper case letter `X` always keep the same.

# Expected behavior

The lower case letter `x` in a hexadecimal number should be displayed the same as well as any other cases.

# Actual behavior

The lower case letter `x` in a hexadecimal number is displayed like a multiplication sign.

**Comment by aaronbell** [comment] 2020-06-29 06:32
Hi, this is a dupe of #285 and will be changed in an upcoming release.

**Closed by aaronbell** 2020-06-29 06:32 UTC
