### ISSUE TITLE
Create chocolatey package for the font

### ISSUE THREAD

**Issue by AxCoder** [microsoft/cascadia-code#123] opened 2019-09-26 09:25 UTC
http://chocolatey.org is a package manager for windows. Please, create a package for installing this font. There are [some examples](https://chocolatey.org/packages?q=font)  in the repository.

In will help to prepare development environment on new machines

**Comment by aaronbell** [comment] 2019-09-26 16:31
Duplicate of #35

**Closed by aaronbell** 2019-09-26 16:31 UTC
Labels: Issue-Feature
