### ISSUE TITLE
The Anaconda enviroment symbol

### ISSUE THREAD

**Issue by wangtong321** [microsoft/cascadia-code#286] opened 2020-05-31 09:30 UTC
In windows terminal (powerline), the Anaconda enviroment symbol can not show.
![image](https://user-images.githubusercontent.com/40911583/83348995-d17de500-a363-11ea-8928-2f22af0a0f90.png)

And I set the font
```
 "defaults":
        {
            // Put settings here that you want to apply to all profiles.
			"acrylicOpacity": 0.7,
			"colorScheme" : "Frost",
			"cursorColor" : "#000000",
			"fontFace" : "Cascadia Mono PL",
			"useAcrylic": true
        }
```

**Comment by aaronbell** [comment] 2020-06-01 21:13
The Anaconda environment symbol is covered under the full NerdFonts character set which we unfortunately do not have support for at this time. As this is a dupe of #194, I am closing. Thanks!

**Closed by aaronbell** 2020-06-01 21:13 UTC
Labels: Issue-Feature
