### ISSUE TITLE
Support Greek language and in general all Unicode glyphs/letters

### ISSUE THREAD

**Issue by PhilipHassialis** [microsoft/cascadia-code#100] opened 2019-09-22 12:59 UTC
The font is an interesting take on monospace but the problem is that it doesn't cater to multilingual audiences. Is there a chance to have support for all languages like e.g. Consolas, SF Mono or whatnot?

**Comment by ExE-Boss** [comment] 2019-09-24 14:30
Duplicate of #33

**Closed** 2019-09-24 17:52 UTC
Labels: Issue-Feature, Resolution-Duplicate
