### ISSUE TITLE
The problem with using the "visible tabs" or "visible spaces" feature

### ISSUE THREAD

**Issue by AlekseyU** [microsoft/cascadia-code#119] opened 2019-09-25 10:42 UTC
I am using an IDE with settings "visible tabs" or "visible spaces".
In case of "visible tabs" the IDE shows the "double arrow" character.
In case of "visible spaces" the IDE shows the dot at the middle of the row.
![dots_and_tabs](https://user-images.githubusercontent.com/55789597/65593584-75bfb880-df99-11e9-9ff8-aa52d15af73a.png)

Unfortunately, the cascadia-code font doesn't have this characters and displays
![dots_and_tabs_cascadia](https://user-images.githubusercontent.com/55789597/65593568-6c365080-df99-11e9-903d-2847462e21cd.png)
Could you please fix this?

**Comment by aaronbell** [comment] 2019-09-25 16:36
Duplicate of #70

**Closed by aaronbell** 2019-09-25 16:36 UTC
