### ISSUE TITLE
Character ≡ missing

### ISSUE THREAD

**Issue by MovGP0** [microsoft/cascadia-code#170] opened 2019-11-04 16:46 UTC
# Description of the new feature/enhancement (with images if possible)

The character ≡ (`&equiv;` Hex 0x2261) is missing. 

This character is used ie. in [POSH-GIT](https://github.com/dahlbyk/posh-git) to indicate that the current Git branch is identical to the remote branch, and therefore used by many developers. 

# Proposed technical implementation details (optional)

Implement the character in the font.

**Comment by DHowett-MSFT** [comment] 2019-11-04 17:57
This is a duplicate of #117.

**Closed by DHowett-MSFT** 2019-11-04 17:57 UTC
Labels: Issue-Feature
