### ISSUE TITLE
Add bolt glyph icon to Cascadia Code PL

### ISSUE THREAD

**Issue by fcaraujo** [microsoft/cascadia-code#445] opened 2021-04-12 03:06 UTC
Hi team, I'd like to suggest the bolt glyph to be added on the Powerline:

![image](https://user-images.githubusercontent.com/553927/114335127-3b7c3300-9ba0-11eb-8b31-c49d462e4de7.png)

I followed @shanselman guide to use windows terminal with Cascadia Code including Powerline.
So I installed `Cascadia Code 2102.25` and it looks great, however, while running on admin mode there's no bolt in front of the line:

![image](https://user-images.githubusercontent.com/553927/114334499-c4926a80-9b9e-11eb-8c93-a0d268944c80.png)

Looking for some workaround I found on [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts#patched-fonts) the `CaskaydiaCove` and it looks like this:

![image](https://user-images.githubusercontent.com/553927/114334554-e2f86600-9b9e-11eb-9790-6e46ce9509cb.png)

Thank you

**Comment by DHowett** [comment] 2021-04-12 15:39
This is a /duplicate of #194

**Closed by DHowett** 2021-04-12 15:39 UTC
Labels: Issue-Feature
