### ISSUE TITLE
Support for german umlauts / special characters like ä, ö, ü and ß.

### ISSUE THREAD

**Issue by selmaohneh** [microsoft/cascadia-code#79] opened 2019-09-20 10:31 UTC
The german language contains some special characters called umlauts. Those characters are

* ä and Ä
* ö and Ö
* ü and Ü
* ß

Right now these characters are not supported. The mix of supported and not supported characters looks kind of ugly:

![grafik](https://user-images.githubusercontent.com/29881939/65320530-56441c80-dba2-11e9-9462-fee837afdc2e.png)

That's way I'd like to see these characters supported / implemented.

Thanks in advance!

**Comment by ExE-Boss** [comment] 2019-09-20 11:12
Duplicate of #33

**Comment by selmaohneh** [comment] 2019-09-20 17:31
> 
> 
> Duplicate of #33

Kind of, you're right. But #33 even requests the whole ISO-8859-1... maybe it would be possible to get the german ä, ö, ü and ß sooner?

If not, feel free to close the issue.

**Comment by cklutz** [comment] 2019-09-23 06:08
Also, this is additionally annoying in the console itself. Where there is no font replacement for missing characters and you only get "boxes" instead.

**Closed** 2019-09-25 19:55 UTC
Labels: Issue-Feature
