### ISSUE TITLE
En dash showing in PowerShell directory listings in Windows Terminal

### ISSUE THREAD

**Issue by twwilliams** [microsoft/cascadia-code#62] opened 2019-09-19 14:43 UTC
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: Windows Terminal (Preview) v0.4.2382.0
OS platform and version: Windows 10 Pro 10.0.18362 N/A Build 18362
Screen resolution (i.e. 220dpi): 3840 x 2160 / 125% scale
```

# Steps to reproduce

Display the contents of a directory in PowerShell:

```
> dir
```

# Expected behavior

The Mode should be displayed with all hyphens:

d-----
-a----

# Actual behavior

The character after the letter (and before in the case of a) is an en dash instead of a hyphen:

![image](https://user-images.githubusercontent.com/1378042/65254311-50264100-dab9-11e9-9768-7c0c08cbe78c.png)

The en dash is also slightly lower than the hyphen.

**Comment by cerebrate** [comment] 2019-09-19 19:13
I believe that's actually a ligature side-effect. The first character after the letter is the hyphen; the following ones are Cascadia's -- or --- ligatures. You can see this happening yourself if you type multiple hyphens at a prompt; doesn't matter which, behavior is the same in PS, zsh, or cmd.

A similar side-effect can be seen if you use the > character at the end of your prompt and type a hyphen, thus:

![prompt-ligation](https://user-images.githubusercontent.com/371623/65273792-95616780-dae7-11e9-9d31-b51e754eaeaf.jpg)

...where a single hyphen ligates with the prompt.

**Comment by twwilliams** [comment] 2019-09-19 19:16
Right. It's a deliberate ligature. It corrects itself when typing at the command line but isn't corrected on program output.

**Comment by cerebrate** [comment] 2019-09-19 19:25
I think that just depends on the surrounding text. If you type the relevant bit of the PS output at the command line, you get the same semi-ligated result:

![nocorrect](https://user-images.githubusercontent.com/371623/65274502-0e14f380-dae9-11e9-86ee-e219140d4316.jpg)

**Comment by twwilliams** [comment] 2019-09-19 19:27
You're right. It shows up with one hypen, goes way with two, and then returns with four or more.

**Comment by aaronbell** [comment] 2019-09-21 12:49
At current the font doesn't actually contain an en-dash or em-dash. If the editor is automatically swapping two hyphens for an en-dash or em-dash, it may be that you're seeing font fallback to a different font where the height of the dashes is different. All the dashes in Cascadia Code are at the same height. 

Anyway, I'll be sure to add those in and it should get sorted out :)

**Comment by DHowett-MSFT** [comment] 2019-09-22 17:21
@aaronbell It looks like this is actually because of the substitution for `[lowercase letter]` followed by `-` (to `hyphen.lc`). Fira Code acts the same here.

![image](https://user-images.githubusercontent.com/14316954/65391840-80bce380-dd22-11e9-80d9-22da96ce3faa.png)

**Comment by DHowett-MSFT** [comment] 2019-09-22 17:22
Since Fira does the same thing, I'm inclined to close this "by design". Dropping the hyphen to meet a lowercase character is likely to be broadly incompatible with powershell's mode listing.

**Comment by mdtauk** [comment] 2019-09-22 17:29
Is this about alignment with lowercase versus uppercase?  

If you were to add an Opentype substitution rule for a hyphen following a hyphen.lc glyph, that should keep the preceding hyphens aligned.  

A Space or Uppercase character would then swap it back to it's uppercase and numeric alignment.

**Comment by aaronbell** [comment] 2019-09-22 18:45
Ahh, I see. I misunderstood. It seems to me that @mdtauk's solution seems like a good one. It would at least look consistent within a single run of lowercase-specific characters.

**Comment by aaronbell** [comment] 2019-09-23 21:07
I'm thinking about this further, and thinking it might make sense to remove the case sensitive features entirely (as it is a "nice to have" feature) rather than looking to account for every circumstance where there will be mismatches between the ligature set and the hyphen. 

Any concerns with this?

**Comment by mdtauk** [comment] 2019-09-23 21:13
I think there is something to be said for including it, as coding is not just about words and the typical reading and sentence structures.

Symbols and operators have meaning, and visually aligning them to the text surrounding is very nice.

But consistency and trying not to add confusion to the meaning and intent.

These fonts also have drawing glyphs, and hyphens and bars get used for treeviews etc.

I'm not wedded to them, but if they can be made to work, it's a nice character of the type family

**Comment by aaronbell** [comment] 2019-09-23 21:23
Makes sense. What I'm trying to solve for is a situation where a lowered form is followed by another element that should then be ligated. For example `a->`. In that case, we would see this:

`a-` (low hyphen)
`a->` (normal ligature)

So I'm trying to (a) avoid a situation where the height of the hyphen jumps up and down as a user types, and (b) needing to create lowercase versions of most all the ligatures. 

I think that it might be better to remove them for now, and then revisit the implementation later. If nothing else but to provide more consistent and expected text entry and rendering.

**Comment by mdtauk** [comment] 2019-09-23 22:06
Other Opentype fonts handle lowercase punctuation as the default, and handle uppercase as their own thing.

Code is mostly lowercase (ignoring Assembly, and other edge cases) as well as numerals.  So until you are able to include it in a great way, I would suggest optimising for lowercase initially, or centre all symbols in the vertical space and treat them as iconic, rather than topographic

**Closed** 2019-10-02 18:49 UTC
