### ISSUE TITLE
Feature Request  Can you please make 4 normal?

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [microsoft/cascadia-code#231] opened 2020-01-13 21:45 UTC
Hi there, 
Obviously great job with these fonts, visible, better looking..great in any way. There is however one minor issue I'm experiencing with it. The character 4 is the only "open" character and it's highly distracting. Can you please make it normal like all the other characters?
Thanks!

**Comment by DHowett-MSFT** [comment] 2020-01-13 21:46
This is a duplicate of #66.

**Closed by DHowett-MSFT** 2020-01-13 21:46 UTC
Labels: Issue-Feature

**Comment by Vulgaris-Viridis** [comment] 2020-01-13 21:47
Well that was quick :) Sorry, haven't seen it. Thank you.
