### ISSUE TITLE
VSCode does not utilize italic font, defaults to artificially slanted

### ISSUE THREAD

**Issue by derekschinke** [microsoft/cascadia-code#485] opened 2021-05-29 23:46 UTC
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (static)

### Platform

macOS 11.4

### Other Software

Visual Studio Code 1.56.2

### What happened?

Italic font does not appear in VSCode themes that use italics.

Settings:
![Screen Shot 2021-05-29 at 19 42 12](https://user-images.githubusercontent.com/16145903/120087445-f8294580-c0b5-11eb-93f3-f09472efab0c.png)

Result:
![Screen Shot 2021-05-29 at 19 42 44](https://user-images.githubusercontent.com/16145903/120087450-0b3c1580-c0b6-11eb-8b3c-5644ed7c51c4.png)

Italics are rendered as Cascadia Code, but slanted artificially by VSCode, instead of using the bespoke Cascadia Code Italic.

**Comment by sonulohani** [comment] 2021-05-30 00:29
Even I am also facing the same. Seems like the problem is with the font naming. For now you can use the fonts inside ttf folder(there are 8 fonts) instead of ttf/static. That works fine for me.

**Comment by Someone-Of-Liu** [comment] 2021-05-30 03:21
Maybe you can install the Windows Terminal in Microsoft store. It comes with a Cascadia code and others, and the font will stay up to date. Then set Font Family to Cascadia Code and no Cascadia Code Italic

**Comment by derekschinke** [comment] 2021-05-30 03:23
@Someone-Of-Liu 

> ### Platform
> macOS 11.4

No Microsoft Store on macOS 😅

**Comment by Someone-Of-Liu** [comment] 2021-05-30 03:26
Sorry😂
________________________________
发件人: Derek Schinke ***@***.***>
发送时间: Sunday, May 30, 2021 11:23:59 AM
收件人: microsoft/cascadia-code ***@***.***>
抄送: 刘志军 Liu Zhijun ***@***.***>; Mention ***@***.***>
主题: Re: [microsoft/cascadia-code] VSCode does not utilize italic font, defaults to artificially slanted (#485)


@Someone-Of-Liu<https://github.com/Someone-Of-Liu>

Platform

macOS 11.4

No Microsoft Store on macOS 😅

**Comment by yume-chan** [comment] 2021-05-31 01:56
I think you should swap the order, the font renderer uses the first font that contains the character.

**Comment by derekschinke** [comment] 2021-05-31 01:58
Unfortunately, that makes everything italic:
![Screen Shot 2021-05-30 at 21 58 42](https://user-images.githubusercontent.com/16145903/120129557-3431d880-c192-11eb-9e34-a736d81093c5.png)

**Comment by aaronbell** [comment] 2021-05-31 04:27
There's been an issue with the static instance naming (see #481). I recommend using the variable font version of the font for the time being rather than the static installs until a new release is pushed. At that point, you will only need to state "Cascadia Code" to get both the upright and italic forms. 

As this appears to be a dupe of #481, I will close this one.

**Closed by aaronbell** 2021-05-31 04:27 UTC
