### ISSUE TITLE
Font shows in mac office (Outlook/Word) as garbled characters

### ISSUE THREAD

**Issue by nz4ypt** [microsoft/cascadia-code#329] opened 2020-07-16 16:00 UTC
# Environment

```none
Cascadia Code version number: 2007.01
Application (with version) used to display text: mac Outlook 16.38, mac Word 16.38
OS platform and version: catalina 10.15.5
Screen resolution (i.e. 220dpi): 4k HiDPI at 200% scaling (1920x1080@2x)

Any other software? These fonts work fine in mac Excel. Same version (16.38)
```

# Steps to reproduce

Open a new word document, or new email, change font to any of the Cascadia family (code/mono/pl/..), then start typing. garbled chars start to show up.

The names of the fonts from the drop-down list in Outlook or Word are also showing as garbled fonts. They are not recognizable but you know they are the 4 Cascadia fonts installed.

# Expected behavior

Should not expect garbled chars show up.

# Actual behavior

garbled font name shown in the drop-down list. when selecting one of them, the fonts in main document will become garbled texts as well. 

<img width="899" alt="screenshot1" src="https://user-images.githubusercontent.com/6556272/87694109-c50aeb80-c75b-11ea-9844-814fc112aca4.png">
<img width="865" alt="screenshot2" src="https://user-images.githubusercontent.com/6556272/87694113-c5a38200-c75b-11ea-9c8a-1bb5ab47e944.png">

**Comment by aaronbell** [comment] 2020-07-16 17:28
Well that's pretty weird. 

I'm not seeing the issue with the font drop down menu, but I can repro the text entry bug. Will contact the Office Mac folks.

**Comment by DHowett** [comment] 2020-07-16 20:24
I wonder if there's a meaningful difference between the OTF and TTF versions? @nz4ypt which version did you install?

**Comment by nz4ypt** [comment] 2020-07-16 21:12
@DHowett Thank you! That did make a difference. I installed TTF earlier. I re-installed OTF fonts and now able to display properly in the documents.

<img width="250" alt="Screen Shot 2020-07-16 at 5 05 58 PM" src="https://user-images.githubusercontent.com/6556272/87723006-17153680-c787-11ea-898e-cb781cf92ff5.png">


However, in the drop-down list, I still see the bad names for each fonts. but when you have one selected, it then shows ok in the text box (like shown in above screen). I tried to remove all fonts, reboot, and add back OTF again, but same issue.

<img width="250" alt="Screen Shot 2020-07-16 at 5 06 33 PM" src="https://user-images.githubusercontent.com/6556272/87723057-2f855100-c787-11ea-9699-2901f8a35a3b.png">

**Comment by aaronbell** [comment] 2020-08-05 15:28
Hi! The folks over in Office have asked if you could send a Word doc that is exhibiting the problem with the font embedded that they could use for testing. Would you be able to provide that? Thanks!

**Comment by aaronbell** [comment] 2020-08-11 18:25
Unfortunately, we have not been able to repro what you're observing. It might be a font cache issue, but without a repro case, the Office folks can't investigate. As such, I'm closing this bug.

**Comment by jjeskovs** [comment] 2020-11-27 02:37
I have the same issue, 
[Hgvcjkjkjbb.docx](https://github.com/microsoft/cascadia-code/files/5605697/Hgvcjkjkjbb.docx)
please attached word document.

**Comment by aaronbell** [comment] 2020-11-27 22:27
Verified that the attached word doc appears to show the issue.

**Comment by aaronbell** [comment] 2020-11-28 01:48
(I’ve forwarded the test case off to Office to take a look).

**Comment by aaronbell** [comment] 2020-12-03 16:17
@jjeskovs Can you zip the font file itself and attach it here? Thanks!

**Comment by dougwhitemappen** [comment] 2021-02-02 06:43
Came across this issue while trying to resolve the exact same problem our customers were having with RobotoSlab.

I was able to reproduce the issue with Cascadia Code 2007.01 release, and then with the 2009.22 release.
I believe that Office is having problems with extracting font weights from a single .ttf file.

With the 2009.22 release you guys included a `static` folder with the individual files for each of the font weights, so I've only got a fix for that release, but I think I have identified the problem.

By uninstalling (`./ttf/CascadiaCode.tff`) and installing the font weights individually (`./ttf/static/CascadiaCode-*`) I was able to fix the issue and render the fonts correctly. Similarly, reversing back to the combined font re-introduces the problem.

The font files are located in `~/Library/Fonts` so this is scriptable.

*Note: You need to fully restart Word to get it to rebuild the font cache.*

**Comment by aaronbell** [comment] 2021-02-02 06:54
Thanks Doug. I am still awaiting final confirmation from the Mac Office team, but it appears that the problem is related to a disconnect between the postscript naming convention and how Mac Office enumerates the names for the different weights. 

I believe I have a fix for this which will be included in the next release of the font. Then you will be able to use the variable font version again :).

**Closed** 2021-02-09 01:13 UTC

**Comment by thlinard** [comment] 2021-02-12 00:43
> Thanks Doug. I am still awaiting final confirmation from the Mac Office team, but it appears that the problem is related to a disconnect between the postscript naming convention and how Mac Office enumerates the names for the different weights.
> 
> I believe I have a fix for this which will be included in the next release of the font. Then you will be able to use the variable font version again :).

Hi @aaronbell 

The problem affects every VF from Google Fonts too (tested with Word 16.45 on macOS 10.15.7), is there a way to contact the Mac Office team? I can easily provide sample files.

Otherwise, will the fix scheduled in the mid-Feb update require the type of changes you have made (nameID 4, 6, 17 and 25) to work? If so, I can let the Google team know.

**Comment by aaronbell** [comment] 2021-02-12 03:04
@thlinard 

I actually sent an inquiry asking about what changes are being made at the start of the month, but haven't heard back. Have sent a follow up. 

However, that aside, I think that the modifications I made to the name table are sufficient to resolve the issue. 

In the case of Cascadia Code, the Mac Office's system previously detected the PostScript name as "Cascadia-Code", but all of the font variants were being read in the form of "CascadiaCode-Regular", or "CascadiaCode-Bold". 

So the key change that I made was the addition of name table 25. My belief is that use of that field informs the system what the root PostScript name should be (rather than whatever the existing PostScript name is set to). It probably also helped to set name table 6 to drop the "-Regular", but my understanding is that with the presence of 25, it shouldn't have an impact. 

Use of "Roman" is for other reasons unrelated to this issue.

**Comment by thlinard** [comment] 2021-02-12 11:53
Hi @aaronbell 

> However, that aside, I think that the modifications I made to the name table are sufficient to resolve the issue.

Well, not quite. Here are the menu with the new 4 VF fonts installed (CascadiaCode-2102.03, TTF VF version – the static are fine, of course –, Word 16.45, macOS 10.15.7):

<img width="335" alt="Cascadia Code-Menu" src="https://user-images.githubusercontent.com/13808824/107763542-151c5180-6d2f-11eb-9ea5-4def4233bda6.png">

The text ("When zombies arrive, quickly fax judge Pat" for the record, even if at this level, the information is hardly useful):
<img width="942" alt="Cascadia Code-Text" src="https://user-images.githubusercontent.com/13808824/107763671-4563f000-6d2f-11eb-84cf-192b28b3c9be.png">

> So the key change that I made was the addition of name table 25. My belief is that use of that field informs the system what the root PostScript name should be (rather than whatever the existing PostScript name is set to). It probably also helped to set name table 6 to drop the "-Regular", but my understanding is that with the presence of 25, it shouldn't have an impact.

Yes, I saw that with your changes, `nameID 4` + `17` = `nameID 6` = `nameID 25` (in the variation of a space or a hyphen).

If Word for Mac specifically asks for this, why not, it won't be much to fix. But I doubt that adding `nameID 25` is enough.

[I convinced Marc Foley from Google Fonts last year](https://github.com/google/fonts/issues/2391#issuecomment-642923536) to improve their `STAT` table, and that involved adding a `nameID 25` (and `postscriptNameID` for the `NamedInstance` of the `fvar` table, which you don't do for Cascadia). It was about fixing bugs with Photoshop and InDesign, so now all new VFs that come out of Google Fonts have a `nameID 25`. And I assure you, that's not enough to solve the support issue in Word for Mac: they all look the same as in the two screenshots I just posted.

**Comment by aaronbell** [comment] 2021-02-12 14:20
Well I don’t quite know what to tell you. I followed the name table structure of https://github.com/adobe-fonts/source-code-pro, which worked correctly on my machine. And in my tests, I did not observe any problems of garbled characters while using the new versions of Cascadia Code.

**Comment by thlinard** [comment] 2021-02-12 14:50
> Well I don’t quite know what to tell you. I followed the name table structure of https://github.com/adobe-fonts/source-code-pro, which worked correctly on my machine.

I believe you're not at fault, the fonts are fine. For the static files, the Panose definition is incorrect, but since so many fonts aren't correct on this point either, it shouldn't have any consequences, or at least not as much.

I think there is a serious bug in Word, and the Mac Office team should be made aware of the extent of the problem.

> And in my tests, I did not observe any problems of garbled characters while using the new versions of Cascadia Code.

Are you using macOS Big Sur? Or a beta version of Word for Mac? English locale or another one?

**Comment by thlinard** [comment] 2021-02-12 16:02
On another machine, 1) I installed the static fonts, 2) opened Word, 3) closed Word, 4) deleted the statics, 5) installed the VFs, 6) opened Word. And there the problem was gone.

**Comment by aaronbell** [comment] 2021-02-12 17:20
As I understand it, the Mac Office team is aware, and is issuing a fix this month to resolve the problem. It seems like we'll need to wait for that fix to have this issue fully resolved. 

I'm on 16.45, still running Mojave in standard US locale. But my understanding is that the inbuilt DWrite implementation in Word is being used, so the base OS shouldn't matter that much. 

Are you able to duplicate the same behavior with Source Code Pro?

**Comment by thlinard** [comment] 2021-02-12 18:23
> As I understand it, the Mac Office team is aware, and is issuing a fix this month to resolve the problem. It seems like we'll need to wait for that fix to have this issue fully resolved.

Yes, certainly.

> I'm on 16.45, still running Mojave in standard US locale. But my understanding is that the inbuilt DWrite implementation in Word is being used, so the base OS shouldn't matter that much.

Very probably. For example, Word doesn't recognize instances of Skia, which is yet the ancestor for all VFs (it was a VF before VFs, even though it doesn't have a `STAT` table but only an `fvar` table), while Apple applications display all of its named instances.

> Are you able to duplicate the same behavior with Source Code Pro?

Yes, with Source Code Pro VF TTF version, 1.018R.

**Comment by thlinard** [comment] 2021-02-17 15:18
Hi @aaronbell

I tested Office for Mac version 16.46 (February 2021 update) today. According to my tests (dummy fonts with fake `nameID`), the implementation is a mix between the `fvar` and `STAT` tables: the named instances are the `NamedInstance` of the `fvar` table but their names are not extracted from their `subfamilyNameID`, but are built from the `ValueNameID` attached to the `AxisValue` of the `STAT` table  (which is quite… surprising, and sometimes gives the same result as the `subfamilyNameIDs`, but sometimes not…).

Cascadia Code 2102.03 works fine, but version 2009.22 also: `nameID` 25 doesn't seem to be used (but your changes weren't for nothing: they are useful for Photoshop and InDesign, with their rather flawed implementations of the VF specs).

If the fonts have been installed before, the contents of the following folders must be deleted:

1. ~/Library/Containers/com.microsoft.XXX/Data/Library/Application Support/Microsoft/FontCache
2. ~/Library/Containers/com.microsoft.XXX/Data/Library/Application Support/Microsoft/FontPreviewCache

Where "XXX" is the application's name (e.g. ~/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/FontPreviewCache).

**Comment by aaronbell** [comment] 2021-02-17 17:18
@thlinard Thanks for reviewing the update and font! I hadn't realized a new version was released today.

It would have been nice if the team had been more forthcoming with what the update actually does rather than needing to figure things out after the fact, but I'm glad that it seems like the update has solved the problem.
