### ISSUE TITLE
Case feature misfires in some contexts

### ISSUE THREAD

**Issue by madig** [microsoft/cascadia-code#109] opened 2019-09-23 14:58 UTC
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: Windows Terminal (Preview) Version 0.4.2382.0
OS platform and version: WIndows 10 1903
Screen resolution (i.e. 220dpi): 96dpi
```

# Steps to reproduce

In e.g. Terminal, list some directory contents.

# Expected behavior

In the "Mode" column, the dashes should be aligned with each other

# Actual behavior

The dash in front of and after a character is lowered.

![image](https://user-images.githubusercontent.com/380829/65436701-73832000-de1a-11e9-9a86-aa13ab760168.png)

**Comment by DHowett-MSFT** [comment] 2019-09-23 15:11
Duplicate of #62

**Closed by DHowett-MSFT** 2019-09-23 15:11 UTC
