### ISSUE TITLE
"y" looks "a bit unfinished"

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/cascadia-code#8] opened 2019-07-29 23:47 UTC
> The bottom corner of the "y" looked a bit unfinished - sort of like a "v" that accidentally got a descender.
> ![498be96a-7910-43d0-a8da-1c88f2416a28](https://user-images.githubusercontent.com/14316954/62090161-b3fe5d00-b220-11e9-885a-d30538edf1cb.jpg)

_from @mdtauk_

**Comment by fitojb** [comment] 2019-09-21 18:57
It’s a style in typography; it’s not a bug.

**Comment by mdtauk** [comment] 2019-09-21 21:58
Was that a comment I made?

**Comment by DHowett-MSFT** [comment] 2019-09-21 22:05
I’m fairly sure, but I can’t find the original source. You also remarked on the side bearings on the m/M in the same source comment. Maybe it was on Twitter?

**Comment by mdtauk** [comment] 2019-09-21 22:15
> I’m fairly sure, but I can’t find the original source. You also remarked on the side bearings on the m/M in the same source comment. Maybe it was on Twitter?

Hmm, @bitcrazed  transferred over the thread I started in the Terminal repo #74 which has the comments about the narrow and crushed m...

And I can only see three tweets with Cascadia mentioned.

Eitherway I don't think the y looks like a V with an accidental descender, the cut out is both an ink trap, and a character quirk for the glyph so consider this closed, if it was a comment I made.

**Comment by dasMulli** [comment] 2019-09-23 20:04
> It’s a style in typography; it’s not a bug.

Like Chagall paintings, it may be a form of art, but I don't want it in my home.

but srsly at some point there will need too be some form of guidelines as to (who/) how a decision is made about some visual design.. e.g. my issue is with the "4" (https://github.com/microsoft/cascadia-code/issues/66) that is mostly a design issue I have with it, not a technical one.
While I think the y looks ok when small, increasing the font size for presentations makes this visible and once you see it, you cannot unsee it.

**Closed** 2019-09-24 17:30 UTC
Labels: Area-Glyphs, Resolution-By-Design

**Comment by tabatkins** [comment] 2019-10-03 00:11
Ink traps are relevant for *printing*, particularly small text on low-quality paper, not displaying on a screen, right? All of the example of ink traps I see on the Wikipedia page look *bad* in a way that I think is hard to argue with (but would look good in print due to ink spreading, as that's their whole point).

I agree that this isn't very noticeable at standard code sizes (tho now that I know about I'm seeing it normally, ugh) but would be very noticeably when blown up. It definitely looks like a v with a descender attached.

This might be more related to the request for a "Display" variant of the font (#91), tho; I'd definitely expect a Display variant to *not* contain any ink traps, at least.

**Comment by mdtauk** [comment] 2019-10-03 01:36
The Ink Traps also help with hinting, to keep edges crisper.

**Comment by aaronbell** [comment] 2019-10-03 03:15
@tabatkins Ink traps are just as useful on screen as they are in print—perhaps there isn't ink spread, but too much weight can result in more, darker pixels. By building in ink traps one is able to actually reduce the darkness of pixels at key spots in a letterform and enable more even color to the letterforms. 

@dasMulli Cascadia Code, at present, is definitely designed for small scale use, so some of the design features designed to help reduce weight, or better fill the space, are really only intended for smaller sizes. I would argue that the /y isn't a totally unusual design feature (I've seen it on many other letters) but I can understand how you don't enjoy it.

**Comment by dasMulli** [comment] 2019-10-03 05:04
> but I can understand how you don't enjoy it.

Give me a month of getting used to it 😅. I don't have any hard feelings about it.

I mostly only wanted to bring up how decisions are made according to style. For example, the 4 glyph follows american/british handwriting that is unnatural to other parts of the world. Other decisions, like this issue being discussed, is purely a decision of tase. This being an open source project by design, it is hard to reach a decision without guidelines. E.g. is it ok to follow styles that mostly Americans are used to (4) or have design decision with community input. I mean I can't possibly create a sensible unit test that reproduces a bug or anything 🤣

**Comment by Vulgaris-Viridis** [comment] 2020-01-14 12:18
> Give me a month of getting used to it

Sadly that doesn't work for me, i tried to ignore it but it is too distracting. I will be reverting to the Consolas.
