### ISSUE TITLE
VirtualEnvSymbol missing from the PL fonts.

### ISSUE THREAD

**Issue by jaisharx** [microsoft/cascadia-code#351] opened 2020-08-28 02:05 UTC
**Cascadia Code Version:** V2007.001
**OS:** WIN10 Build 19041.450

Hi, I'm using the PL version of fonts available. It works great. All the extra symbols are available except the virtual-environment symbol (it's the only one missing). It would be amazing if you guys can fix it, would make cascadia fonts my first choice then. Thanks. 

**Image of how the missing symbol looks:**

![py](https://user-images.githubusercontent.com/55892116/91511960-83469680-e8fe-11ea-860e-2da5d145830f.png)

![missing](https://user-images.githubusercontent.com/55892116/91512573-f13f8d80-e8ff-11ea-85e2-5cda00315030.png)

**Comment by aaronbell** [comment] 2020-08-28 17:17
Thanks for the comment! This appears to be a dupe of #210 

Essentially, we haven't been able to add the u+eXXX glyphs (of which this is one) as they're part of the larger Nerd Font set. Once I have approval to do so, I'd be happy to add it :)

**Closed by aaronbell** 2020-08-28 17:17 UTC
Labels: Issue-Feature
