### ISSUE TITLE
Font version without ligatures

### ISSUE THREAD

**Issue by xvoidee** [microsoft/cascadia-code#129] opened 2019-09-28 14:07 UTC
# Description of the new feature/enhancement (with images if possible)

Font version (as separate file) without ligatures

**Comment by mdtauk** [comment] 2019-09-28 15:52
Ligatures are normally controlled in the software.  So an option in Windows Terminal, Notepad or Visual Studio to turn ligatures off or on.

VS Code already has such an option.

**Comment by lhutyra** [comment] 2019-09-28 16:38
Is it possible to turn off in Visual studio 2019?

**Comment by gnuvince** [comment] 2019-09-28 19:41
> Ligatures are normally controlled in the software. So an option in Windows Terminal, Notepad or Visual Studio to turn ligatures off or on.

Some software doesn't allow disabling ligatures (e.g., Firefox). And even if all software allowed ligatures to be disabled, that requires the user to reconfigure each program they use. It's better to put the onus of disabling ligatures on the Cascadia build system and provide an extra download for users who prefer not to have ligatures, like [Iosevka Term](https://github.com/be5invis/Iosevka/).

**Comment by cata0309** [comment] 2019-09-29 03:14
@Ihutyra it is not possible to disable them in Visual Studio IDE. I opened 2 issues on the Visual Studio IDE issue tracker requesting a way to disable them(I was studying for my CS exams and I couldn't afford to get used to them).
My issues got their atention but this is just about it, there is no more info or help.
Issue 1(closed because "there was not enough info" even if it was clear what I was requesting) : https://developercommunity.visualstudio.com/content/problem/381629/ligatures.html

Issue 2: https://developercommunity.visualstudio.com/idea/536053/how-to-completely-disable-font-ligatures-feature-o.html

**Comment by xvoidee** [comment] 2019-10-08 11:13
> 
> 
> Ligatures are normally controlled in the software. So an option in Windows Terminal, Notepad or Visual Studio to turn ligatures off or on.
> 
> VS Code already has such an option.

No
Only minor amount of software allows to control ligatures. There are many editors/terminals/etc which use fonts as-it-is. So separate version of font needed!

**Comment by chiniara** [comment] 2019-10-11 04:35
I posted this exact same issue and it was ignored and closed.

I hope this time it works out :)

**Comment by aaronbell** [comment] 2019-11-12 03:50
Thanks! I'm closing this as a duplicate of #80. But never fear as a version without ligatures is in the plans :).

**Closed by aaronbell** 2019-11-12 03:50 UTC
Labels: Issue-Feature
