### ISSUE TITLE
Publish to Windows Store

### ISSUE THREAD

**Issue by thomassth** [microsoft/cascadia-code#664] opened 2022-12-18 19:00 UTC
# Description of the new feature/enhancement (with images if possible)

Other fonts from Microsoft like Ariel Nova are on the store, Cascadia code should do as well

# Proposed technical implementation details (optional)

[Example](https://apps.microsoft.com/store/detail/arial-nova/9NS5CT1MZ7M8?hl=en-ca&gl=ca)

**Comment by IllusionMH** [comment] 2023-04-16 00:00
Duplicate of #39

**Closed** 2023-09-18 15:56 UTC
Labels: Issue-Feature
