### ISSUE TITLE
Support for Nordic languages

### ISSUE THREAD

**Issue by irvall** [microsoft/cascadia-code#122] opened 2019-09-26 07:08 UTC
# Description of the new feature/enhancement (with images if possible)

Support for nordic languages (namely, adding ÆØÅ (DK/NO), ÅÄÖ (SE))

# Proposed technical implementation details (optional)

**Comment by madig** [comment] 2019-09-26 09:02
Duplicate of https://github.com/microsoft/cascadia-code/issues/33

**Closed** 2019-09-26 16:31 UTC
Labels: Issue-Feature
