### ISSUE TITLE
Double-equals (==) ligature can be improved to be connected together

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [microsoft/cascadia-code#497] opened 2021-06-06 04:55 UTC
# Description
With Cascadia Code's ligature set aimed at enhancing readability for programmers, the double-equals ligature could be improved to two long horizontal lines (like Fira Code, JetBrains Mono, etc. - see image) to match the ligatures for !=, === and !==.

![image](https://user-images.githubusercontent.com/79387351/120912990-4b0e8880-c6c6-11eb-8413-669781be7f03.png)
![image](https://user-images.githubusercontent.com/79387351/120913003-6a0d1a80-c6c6-11eb-8ab2-88e36e62524e.png)

**Comment by aaronbell** [comment] 2021-06-06 05:25
Dupe of #347. Will likely add a stylistic set for this, but haven't done so yet.

**Closed by aaronbell** 2021-06-06 05:25 UTC
Labels: Issue-Feature
