### ISSUE TITLE
The font can't support "not equal" in lua language in vscode.

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/cascadia-code#98] opened 2019-09-22 07:26 UTC
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: vscode 1.38.1
OS platform and version: win10 x86-64
Screen resolution (i.e. 220dpi): 1920x1080

Any other software?
```

# Steps to reproduce

1.  install the font
2. use the font in vscode and enable font ligatures
3. lua script like below is display wrong:
![image](https://user-images.githubusercontent.com/8075421/65383724-16b93400-dd4c-11e9-86eb-9ffc08c92b86.png)  (Disable Font Ligatures)
![image](https://user-images.githubusercontent.com/8075421/65383739-2fc1e500-dd4c-11e9-95dc-ef66f6c44d88.png)  (Enable Font Ligatures)

# Expected behavior

![image](https://user-images.githubusercontent.com/8075421/65383827-4b79bb00-dd4d-11e9-8103-969cf2022827.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/8075421/65383739-2fc1e500-dd4c-11e9-95dc-ef66f6c44d88.png)

**Comment by ExE-Boss** [comment] 2019-09-24 14:10
Duplicate of #71

**Closed** 2019-09-27 03:00 UTC
