### ISSUE TITLE
Resolution of >= sign is bad.

### ISSUE THREAD

**Issue by abubakarm** [microsoft/cascadia-code#76] opened 2019-09-20 07:24 UTC
# Environment

Cascadia Code version number: 1909.16
Application (with version) used to display text: Visual Studio 2013 Update 5
OS platform and version: Windows 7 SP1
Screen resolution: 1920 * 1080

Any other software?

# Steps to reproduce
![cascadia font](https://user-images.githubusercontent.com/329145/65307462-411abe00-dba1-11e9-9d4f-89c19b3582f8.PNG)

Install cascadia font in the environment mentioned above you will see.

# Expected behavior

Resolution should look as sharp/smooth as the rest of the text around it.

# Actual behavior

Resolution for the >= is not good.

**Comment by ArcEarth** [comment] 2019-09-20 19:04
All the arrow alike character are rendered poorly:
2560x1440 display with 150% DPI scaling, Visual Studio 2019, Font size 12 :

![image](https://user-images.githubusercontent.com/2577491/65352015-8c3fcb80-dbb7-11e9-8dec-6f6a991f2073.png)
![image](https://user-images.githubusercontent.com/2577491/65352041-9c57ab00-dbb7-11e9-87ee-518bc41b4c8e.png)
![image](https://user-images.githubusercontent.com/2577491/65352063-aa0d3080-dbb7-11e9-8aa8-2931be5b8b4a.png)

**Comment by DHowett-MSFT** [comment] 2019-09-20 19:26
Duplicate of #21

**Closed by DHowett-MSFT** 2019-09-20 19:26 UTC
