### ISSUE TITLE
Problem with some characters (Turkish)

### ISSUE THREAD

**Issue by validatedev** [microsoft/cascadia-code#108] opened 2019-09-23 13:34 UTC
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: PyCharm Professional 2019.2.2, Notepad
OS platform and version: Windows 10 1903 18362.356
Screen resolution (i.e. 220dpi): 200 dpi 2160x1440 13"

Any other software? No
```

# Steps to reproduce

Try to write italic style (oblique) with Cascade Code on PyCharm Professional sometimes leads to display problem just the character 'ı'. It prints correct result when I try to write on Notepad upper than size 10 but when try to write something lower than 11, the other Turkish fonts starts to behave weird. Wanna add that there's the alignment problem with big Turkish characters on Notepad bigger than 10 if you look at the screenshots.

# Screenshots
<img width="740" alt="bug" src="https://user-images.githubusercontent.com/29679552/65429747-6288dd80-de1f-11e9-9d6f-ce1226df9688.png">
<img width="680" alt="bug2" src="https://user-images.githubusercontent.com/29679552/65429748-6288dd80-de1f-11e9-9923-e90e5a06c82b.png">
<img width="280" alt="bug3" src="https://user-images.githubusercontent.com/29679552/65429749-63217400-de1f-11e9-84ba-38976122b5fe.png">
<img width="464" alt="oblique10" src="https://user-images.githubusercontent.com/29679552/65429751-63ba0a80-de1f-11e9-8602-3bbb2a4331ad.png">
<img width="461" alt="oblique11" src="https://user-images.githubusercontent.com/29679552/65429752-63ba0a80-de1f-11e9-8a1d-0932cfcb71b9.png">
<img width="464" alt="regular10" src="https://user-images.githubusercontent.com/29679552/65429753-6452a100-de1f-11e9-9cdd-7404e491b919.png">
<img width="466" alt="regular11" src="https://user-images.githubusercontent.com/29679552/65429754-6452a100-de1f-11e9-987f-3f6540d61e06.png">

# Expected behavior

Expecting that the fonts that are Turkish are outputs the correct shape.

# Actual behavior

Sometimes they are correct, sometimes doesn't depending to font size.

**Comment by ExE-Boss** [comment] 2019-09-23 15:26
Duplicate of #33

**Closed** 2019-09-24 17:56 UTC
