### ISSUE TITLE
Italic doesn't work in MacVim

### ISSUE THREAD

**Issue by georgevreilly** [microsoft/cascadia-code#490] opened 2021-06-01 18:12 UTC
Various flavors of Vim support italic fonts in syntax highlighting. However, this doesn't work with `Cascadia Code` or `Cascadia Mono`. It's almost certainly because the italic fonts are in distinct font families.

To reproduce
1. Launch MacVim. I'm running macOS Big Sur 11.4, but I expect this will reproduce on other versions of macOS.
2. Type `:setfiletype flexwiki` to set the current buffer into FlexWiki mode.
3. Enter a line that looks like `This text is _emphasized_ and this is *strong*.`
4. Launch the font dialog: `:set guifont=*`
5. Choose different fonts. Many fonts, including `Source Code Pro`, `JetBrains Mono`, and `SF Mono`
  will show `_emphasized_` in an _italic_ font and `*strong*` in a **bold** font, with the rest in the regular font. The Cascadia fonts handle `*strong*` correctly, but not `_emphasized_`.
 
<img width="864" alt="Screen Shot 2021-06-01 at 11 01 23 AM" src="https://user-images.githubusercontent.com/34297/120370788-ec838c00-c30c-11eb-8556-5a90bad26813.png">

<img width="818" alt="Screen Shot 2021-06-01 at 11 03 26 AM" src="https://user-images.githubusercontent.com/34297/120370837-fad1a800-c30c-11eb-80d8-b7f2e5769f87.png">

**Comment by DHowett** [comment] 2021-06-01 18:19
It would have been very helpful had you filled out the bug template ☹️ 

Which variants of Cascadia did you install? Variable TTF? OTF? Static TTF? Static OTF? WOFF2?

**Comment by aaronbell** [comment] 2021-06-01 19:05
This should be resolved the next time a font release is issued via the fix for #481

**Comment by georgevreilly** [comment] 2021-06-01 19:13
@Dhowett, I poked around in the issues to see if a similar issue had been reported, didn't find any, and clicked `New Issue`. No template appeared, so I wrote it up freeform. 

I installed all the fonts in the `otf/static` directory of `CascadiaCode-2105.24.zip`

**Comment by aaronbell** [comment] 2021-06-01 19:22
Thanks for the additional context. This is definitely a dupe of #481 and will be solved with the next release. I suggest trying the variable font version in the meantime.

**Closed by aaronbell** 2021-06-01 19:22 UTC
