### ISSUE TITLE
No visibility for = sign on terminal

### ISSUE THREAD

**Issue by vipul-vinsol** [microsoft/cascadia-code#80] opened 2019-09-20 11:18 UTC
Environment

Cascadia Code version number: 1909.16
Application (with version) used to display text: Linux Default Terminal
OS platform and version: Ubuntu
Screen resolution: 1366x768 pixels (96 dpi)

Any other software?
Steps to reproduce

cascadia font

Install cascadia font in the environment mentioned above you will see.
Expected behavior
Equal sign should be visible
Actual behavior
Equal sign in not visible at all

**Comment by vipul-vinsol** [comment] 2019-09-20 11:23
After some experimenting, I have found out that it is visible in other application like VSCode but is not in the terminal. I am not sure what is causing this issue

**Comment by zao** [comment] 2019-09-20 11:53
I'm on Ubuntu 16.04.6 LTS, at 110dpi under XFCE with the same problems as the issue author.

With GNOME Terminal 3.20.2., the `<` and `=` signs render as blank, and ` ->` turns into a three-letter wide left-right double arrow (like `⇔`) overlaid on the original `-`.

![double-arrow](https://user-images.githubusercontent.com/260218/65324935-dcb22b80-dbad-11e9-84c2-cb77ca6c9036.png)

As described, the problem does not manifest in VS Code or its integrated terminal.

**Comment by greatquux** [comment] 2019-09-20 12:45
I don't think VTE-based terminals (such as xfterminal or gnome-terminal) support ligatures.  KDE's Konsole does however and it shows up correctly there.  cf https://unix.stackexchange.com/questions/278175/do-any-open-source-linux-terminals-and-fonts-support-ligatures

**Comment by DEMG-DEV** [comment] 2019-09-20 18:00
in gVIM also the = symbols is not showing up. :(

**Comment by DHowett-MSFT** [comment] 2019-09-20 18:10
gVIM needs special configuration to support ligatures.

**Comment by zao** [comment] 2019-09-20 20:41
Is there some sort of fallback in the font missing for it to work in environments that doesn't do ligatures, or is it intrinsic to how fonts with ligatures are made?

If it's intrinsic, is it possible to have a variant of the font that does not have ligatures for use in those rather prolific applications, or at least document the incompatibility if it's unfixable?

**Comment by DHowett-MSFT** [comment] 2019-09-20 20:42
Wha? The fallback for when ligatures aren't supported (or: are disabled!) is to render the individual characters,

**Comment by zao** [comment] 2019-09-20 20:45
So the underlying problem with VTE (and thus GNOME Terminal) is that they incorrectly attempt to implement ligatures, and if they hadn't tried that hard, they would have been rendering individual characters fine?

**Comment by VladimirMarkelov** [comment] 2019-09-21 02:19
> Wha? The fallback for when ligatures aren't supported (or: are disabled!) is to render the individual characters,

Is it possible to have two version of the font(as it is done in Iosevka): one font with all ligatures etc, and another one without ligatures and all the characters of the same width. The latter one is for editors that (a) cannot work with ligatures and (b) forbid to select a font with non-same-width characters - e.g, my gVim refused to use a few fonts or rendered text very ugly until I deleted from those fonts some characters that were wide than the others

**Comment by zao** [comment] 2019-09-23 17:01
I've tested this on a newer version of Ubuntu (18.04.3 LTS) which has a newer VTE, 0.52. The ligatures do no longer appear and individual glyphs render correctly, which is the good kind of fallback.

[This comment](https://github.com/gnunn1/tilix/issues/1743#issuecomment-523792544) claims that the problem was fixed with VTE 0.52 which I can confirm as that's what on my running system, while my original report used VTE 0.44.2 on the previous LTS.

For me the problem is then resolved, "just don't use old glitchy VTE versions". Cheers!

**Comment by aaronbell** [comment] 2019-09-30 01:37
It appears that this issue is essentially a request for two versions of the font to be shipped—one with ligatures and one without. Heard!

**Comment by VladimirMarkelov** [comment] 2019-11-13 04:05
> It appears that this issue is essentially a request for two versions of the font to be shipped—one with ligatures and one without. Heard!

Maybe rename this issue? :) All other issues about adding a version ligatures are closed and links points to this one. But this one's title is "No visibility for sign". That's confusing.

**Closed** 2019-11-20 03:21 UTC
