### ISSUE TITLE
Characters with descent appear trimmed when relying on the font metrics

### ISSUE THREAD

**Issue by antoineco** [microsoft/cascadia-code#417] opened 2021-02-19 10:10 UTC
Characters with a [descent](https://en.wikipedia.org/wiki/Typeface#/media/File:Typography_Line_Terms.svg) such as `gqjp` appear slightly trimmed at the bottom in terminal based applications when relying on the font metrics.

example:

![image](https://user-images.githubusercontent.com/3299086/108486197-1a811b00-729e-11eb-847b-27f05e1419a6.png)

The terminal emulator I use claims it adjusts row spacing _based on the font metrics_, which works well in practice, except with Cascadia Code and Mono. To be more precise, it assumes a row spacing of `-2` with Cascadia Code/Mono, but not with other fonts.

Excerpt from the [`mintty` man page](https://mintty.github.io/mintty.1.html):

> Mintty adjusts row spacing according to the font metrics, to compensate for tight or tall spacing of some fonts [...]

Now bear with me, the terminal emulator could be doing something wrong here, but since I don't have issues with other popular fonts such as Consolas, [`Source Code Pro`](https://github.com/adobe-fonts/source-code-pro) or [`Fira Code`](https://github.com/tonsky/FiraCode) I thought I would ping you folks about it first, before blaming mintty.

# Environment

**Cascadia Code version number**: 2102.003
**Application used to display text:** [wsltty](https://github.com/mintty/wsltty) (mintty) 3.4.4
**OS platform and version**: Windows 10.0.19042.804
**Screen resolution**: 2560x1440 (100% scaling)

# Steps to reproduce

Run the terminal emulator with the following settings, and type `gqjp`.

```ini
Font=Cascadia Code
FontHeight=12
FontWeight=400
```

# Expected behavior

Leading value of `0`, characters are not trimmed:

![image](https://user-images.githubusercontent.com/3299086/108485448-3637f180-729d-11eb-8133-390366915972.png)

# Actual behavior

Leading value of `-2`, characters are trimmed as shown in the issue description:

![image](https://user-images.githubusercontent.com/3299086/108487199-48b32a80-729f-11eb-8c1c-5a5cff29a099.png)
![image](https://user-images.githubusercontent.com/3299086/108491223-ed376b80-72a3-11eb-9d2d-9a0c2b7734c3.png)

I compensate this by adding the following line to my configuration, but I would expect not having to do that.

```ini
RowSpacing=2
```

Example, when switching to Consolas there is no need to adjust row spacing:

![image](https://user-images.githubusercontent.com/3299086/108490877-84e88a00-72a3-11eb-8c80-92b05a25aefb.png)

**Comment by aaronbell** [comment] 2021-02-19 14:46
Thanks for the feedback, it appears that this is a [known issue](https://github.com/mintty/wsltty/issues/257) with mintty. I’ll see if I can help them resolve it. 

My suspicion is that the issue is with their implementation as Cascadia Code works fine everywhere else. As such, I will close this for now, but will reopen depending on what we figure out. Cheers!

**Closed by aaronbell** 2021-02-19 14:46 UTC
