### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by zangxx66** [microsoft/cascadia-code#101] opened 2019-09-22 18:04 UTC
It dont support Chinese so the system has replaced it with SimSun.But SimSun is not suitable for coding.

**Comment by ExE-Boss** [comment] 2019-09-22 20:10
Duplicate of #55

**Comment by Rean1030** [comment] 2019-09-25 01:14
> It dont support Chinese so the system has replaced it with SimSun.But SimSun is not suitable for coding.

很多IDE可以设置多个字体的，你把需要的首选中文字体写在里面，它就会优先显示了。

**Closed** 2019-09-25 20:04 UTC
Labels: Issue-Feature
