### ISSUE TITLE
support persian and arabic

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/cascadia-code#84] opened 2019-09-20 20:14 UTC
I install Cascadia and i found unfortunately this font doesn't support Arabic and Persian.

**Comment by cinnamon-msft** [comment] 2019-09-24 17:58
Duplicate of #33

**Comment by mohd-akram** [comment] 2020-05-06 16:35
@cinnamon-msft Could this be reopened? The other issue was closed.

**Comment by cinnamon-msft** [comment] 2020-06-09 23:10
Good catch, reopened!

**Comment by morezafard** [comment] 2021-05-01 21:14
Why don't you merge this monospace font with cascadia? It supports both persian and arabic too!
https://github.com/rastikerdar/vazir-code-font

**Closed** 2021-06-18 17:37 UTC
Labels: Issue-Feature, Resolution-Duplicate
