### ISSUE TITLE
Support for special characters š, č, ž, ć

### ISSUE THREAD

**Issue by MaTToX3** [microsoft/cascadia-code#105] opened 2019-09-23 09:23 UTC
Slovenia/Croatian/Serbian characters are not supported at the moment:

![image](https://user-images.githubusercontent.com/4114411/65414623-65baa400-ddf4-11e9-9725-01796c28be41.png)

Most of the time those characters are not really used while coding but sometimes we paste plain string (inside HTML for example) and it's quite ugly to see those missing characters.

**Comment by ericmartinezr** [comment] 2019-09-23 13:41
This would be super useful for spanish characters too : á, é, í, ó, ú, Á, É, Í, Ó, Ú, ñ, Ñ. I just tried these characteres and I only see a square symbol :P

**Comment by cinnamon-msft** [comment] 2019-09-24 17:51
Duplicate of #33

**Closed by cinnamon-msft** 2019-09-24 17:51 UTC
Labels: Issue-Feature
