### ISSUE TITLE
virtual machine + remote desktop + vs 2017/2019 and vsc issues

### ISSUE THREAD

**Issue by softwarebear** [microsoft/cascadia-code#388] opened 2020-11-03 12:02 UTC
# Environment

Cascadia Code version number: 2009.014

Application (with version) used to display text: 

Visual Studio 2017

Microsoft Visual Studio Professional 2017 
Version 15.9.28
VisualStudio.15.Release/15.9.28+28307.1274
Microsoft .NET Framework
Version 4.7.03190

Visual Studio 2019

Microsoft Visual Studio Professional 2019
Version 16.7.3
VisualStudio.16.Release/16.7.3+30503.244
Microsoft .NET Framework
Version 4.7.03190

Visual Studio Code

Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

OS platform and version: Windows_NT x64 10.0.17763

Screen resolution (i.e. 220dpi): 4096x2160

Any other software? yes ... but don't think they should be relevant really ... nothing special font related.

# Steps to reproduce

On my office host machine I am running a VM to which I am connected via windows remote desktop app (not mstsc.exe) from my home laptop joined by direct access and natted through the host machine to the guest that is running visual studio X.

I installed the cascadia font successfully on the VM and I can see the six font preview pages fine.

In Visual Studio 2019 I visually choose the font on the dialog.
In Visual Studio Code I type in the correct font name in the settings font field

I can show other fonts and see them change ... but the cascadia mono font features like the 1,l,I thing just aren't present and it obviously is not the font I want but the substitutes it defaults to.

# Expected behavior

I see the cascadia mono font in my editor windows and it doesn't cause any crashes in visual studio 2019/Code.

# Actual behavior

I had the font on screen briefly (maybe half a day) ... but mostly I see other default alternatives in both visual studios and code.

Visual Studio 2017+2019 keeps crashing down to an empty husk that doesn't respond to input and needs to be killed. 

I just want to use a nice font ... how hard can it be ?

**Comment by softwarebear** [comment] 2020-11-03 12:11
Just to prove I can install a font ... and that this is really a problem ...

![image](https://user-images.githubusercontent.com/1684342/97983690-988fe380-1dcd-11eb-9f34-b9eb38db8304.png)

**Comment by softwarebear** [comment] 2020-11-03 12:14
just to prove I can install a font and that it doesn't work ...

![image](https://user-images.githubusercontent.com/1684342/97983949-f3c1d600-1dcd-11eb-81c6-19091032b81f.png)

BTW the font appears as Cascadia Mono Regular in explorer looking at c:\windows\fonts  ... and it always displays the extralight version

**Comment by aaronbell** [comment] 2020-11-03 13:23
Sorry that you're having difficulties! We've seen that Visual Studio, for whatever reason, seems to have some problems with this font—I'm not entirely sure why unfortunately. The issue is being tracked here: #319. I suspect it is actually related to VS' rendering of a variable font, but AFAIK we're still waiting to hear from the team.

**Comment by aaronbell** [comment] 2020-11-03 13:24
One thing you might try is installing the static instances (included in the [download link](https://github.com/microsoft/cascadia-code/releases/tag/v2009.22) and see if they do better for you.

**Comment by softwarebear** [comment] 2020-11-03 17:04
oh dear ... yes ...the same problem in 2017 too though ... 2017 ends up
with one zombie process ... 2019 seems to have two processes one of which
is a zombie but both unresponsive.

A little embarrassing given it's a font for developers ...

**Comment by aaronbell** [comment] 2020-11-03 17:06
As I said, it isn't clear that the problem is the font or the application. Given the technology built into the font, I suspect it is the application. 

This is why we provide the static instances in cases where the variable font version doesn't work.

**Comment by softwarebear** [comment] 2020-11-03 17:20
Hi Aaron,

I was meaning it was a little embarrassing for visual studio team ... but
these things happen ... I'm no perfect developer ... and meant
humorously ... because of the context 8-)

I had only read the first email at the time I replied.

I'll try the static versions as suggested.

**Comment by softwarebear** [comment] 2020-11-03 17:30
I can see the static font in the editor window ... yay ... I'll keep an eye
on it ... with the variable one it just seems to stop displaying after some
short period that I don't notice ... then I get the crashing and suddenly
its rending another font.

**Comment by aaronbell** [comment] 2020-11-03 17:38
Oh good! Yeah, hope it works better for you. 

I feel a bit bad for the VS team. I mean, many of these applications that have been around for years rely on the foundational bits of font technology to stay the same—and when something changes, well, things go boom :x. Hopefully they're able to get it sorted soon! Happily, VS Code (which has a more modern rendering framework) seems to work without issue. 

Closing.

**Closed by aaronbell** 2020-11-03 17:38 UTC
