### ISSUE TITLE
Font not working in Office 2019

### ISSUE THREAD

**Issue by jjeskovs** [microsoft/cascadia-code#393] opened 2020-11-27 03:11 UTC
**Cascadia Code version number:**
2009.22

**Application (with version) used to display text:**
All Microsoft 2019 apps 

**OS platform and version:**
mac Big Sur 11.0.1 and mac Catalina latest version 

**Screen resolution (i.e. 220dpi):** 
the native resolution of MacBookPro 2020 (2560 X1600) 227dpi

Any other software?
Works fine on the same mac in VS Code and iTerm2

# Steps to reproduce
after the initial install of the font, the apps showing what is seen on the screen shots. 

<img width="1121" alt="Screen Shot 2020-11-26 at 8 03 10 PM" src="https://user-images.githubusercontent.com/54291130/100406518-4d12d300-3023-11eb-9d71-bc454edec9cf.png">
<img width="1161" alt="Screen Shot 2020-11-26 at 8 04 31 PM" src="https://user-images.githubusercontent.com/54291130/100406520-4edc9680-3023-11eb-9fb3-fd0782d7b392.png">
<img width="1225" alt="Screen Shot 2020-11-26 at 8 07 53 PM" src="https://user-images.githubusercontent.com/54291130/100406523-4f752d00-3023-11eb-83a0-bc9c887d5d9a.png">
<img width="860" alt="Screen Shot 2020-11-26 at 8 10 59 PM" src="https://user-images.githubusercontent.com/54291130/100406643-96632280-3023-11eb-8a1c-c54b7c22922a.png">

**Comment by aaronbell** [comment] 2020-11-27 22:28
Thanks for the report (and sample file). As this is a dupe of #329, I'll close this one in favor of that one.

**Closed by aaronbell** 2020-11-27 22:28 UTC
