### ISSUE TITLE
Bug Report: Cascadia Code PL is not suitable for GNOME terminal 3.40.0

### ISSUE THREAD

**Issue by Sherlock-Holo** [microsoft/cascadia-code#444] opened 2021-04-09 18:57 UTC
# Environment

```none
Cascadia Code version number: 2102.25
Application (with version) used to display text: GNOME terminal 3.40.0
OS platform and version: Archlinux
Screen resolution (i.e. 220dpi): 
```

![image](https://user-images.githubusercontent.com/10096425/114227491-a6aee500-99a7-11eb-9808-7e3fc0e19844.png)

# Steps to reproduce

1. open the GNOME terminal 3.40.0 and choose font `Cascadia Code PL` with 14 font size.

2. the triangle is not correct

# Expected behavior

the triangle is correct

# Actual behavior

like the screenshot 
![image](https://user-images.githubusercontent.com/10096425/114228063-70be3080-99a8-11eb-8113-c774807dc453.png)
the triangle is not correct

**Comment by aaronbell** [comment] 2021-04-09 22:39
Oooh. I think I know what is happening here. It appears that your rendering engine supports the `rclt` (required contextual alternatives) flag, but doesn't actually respect the type metrics, or is rendering the background other than how the font intends (maybe due to user-added space?). Either way the end result is not ideal. 

I'd introduced this trick as a way to try and solve #310, but there's some other bug going on that is preventing it from working as intended. Not that I think that disabling the `rclt` fix will resolve __this bug__ as font metrics are notoriously difficult to ensure consistent results for (and there will likely *still* be some gaps above and below the triangle), but it'll probably be closer in rendering to the current situation. Maybe I'll just turn it off for now until Windows Terminal improves their rendering (_hint hint @DHowett_)

**Comment by aaronbell** [comment] 2021-04-09 22:40
One other question—do box drawing characters perform as expected, or are those also problematic? 

Thanks!

**Comment by Sherlock-Holo** [comment] 2021-04-10 03:41
> One other question—do box drawing characters perform as expected, or are those also problematic?
> 
> Thanks!

did you mean this 
![image](https://user-images.githubusercontent.com/10096425/114257283-8277f600-99f1-11eb-85d9-687098628bd8.png)
?

it's not easy to find out but yes, it also not expected, the green color should be the same hight as the text

**Comment by aaronbell** [comment] 2021-04-10 04:07
Ah, no. I am referring to glyphs such as [these](https://en.wikipedia.org/wiki/Box-drawing_character).

Honestly, though, the height of the green box is entirely dependent on the rendering engine, and if there's an issue with that, it is due to the rendering engine in GNOME.

**Comment by Sherlock-Holo** [comment] 2021-04-10 04:30
the box drawing characters is higher than the text too 
![image](https://user-images.githubusercontent.com/10096425/114258295-4005e780-99f8-11eb-8db8-c283c9448332.png)

so this problem should let GNOME terminal team fix it?

**Comment by aaronbell** [comment] 2021-04-10 04:37
Box drawing characters will usually tend to be bigger as they're intended to have some overlap. However, yes, I do believe that this is likely an issue with how GNOME is handling perceived text height and highlighting. Cascadia Code has the "useTypoMetrics" flag set, which indicates that the sTypoAscender and sTypoDescender values should be used instead of winAscent and winDescent, which I suspect is what GNOME is using for rendering the text.

As I mentioned, I might just disable the `rclt` code anyway since I'm not sure it is actually accomplishing anything right now, but that's an aside to getting GNOME to render things correctly. 

Mind you, this is all conjecture on my part—I don't have a mechanism to actually test what GNOME is doing, nor knowledge of how their code interprets line heights, so happy to be mistaken here! :)

**Comment by Sherlock-Holo** [comment] 2021-04-17 17:15
I have tried in konsole 
![image](https://user-images.githubusercontent.com/10096425/115121104-81dbf280-9fe3-11eb-8d66-780913d57c1c.png)

there's no problem in it

I think the problem is caused by GNOME terminal

**Comment by aaronbell** [comment] 2021-04-18 04:42
Sounds like it! Thanks for the follow up. I’ll close this bug as the issue is with the environment. :)

**Closed by aaronbell** 2021-04-18 04:42 UTC

**Comment by dantmnf** [comment] 2021-05-05 15:01
I found box drawing characters work well across terminals, but powerline symbols don't.
Konsole:
![image](https://user-images.githubusercontent.com/2252500/117162138-1cff0580-adf5-11eb-8277-fac12d57ec5a.png)
vte:
![image](https://user-images.githubusercontent.com/2252500/117162274-3607b680-adf5-11eb-80cb-8d05ec244b40.png)

Any difference between them?

**Comment by DHowett** [comment] 2021-05-05 15:03
Box drawing characters are standardized and Terminals have either special workarounds for rendering them (by ignoring the instructions in the font) or special detection for font metrics that apply to them.

Powerline symbols are a non-standardized extension stored in the “private use area,” which a terminal can make no assumptions about. Those glyphs aren’t guaranteed to be powerline glyphs in any given font. The box drawing glyphs are guaranteed, and can be treated specially. :)
