### ISSUE TITLE
Wrong rendering of accented letters

### ISSUE THREAD

**Issue by angelog0** [microsoft/cascadia-code#47] opened 2019-09-19 09:13 UTC
I have just tested this font and found that the accented letters are rendered lighter and smaller or as empty box. See [cascadia-example.tar.gz](https://github.com/microsoft/cascadia-code/files/3630319/cascadia-example.tar.gz).

The `cascadia-emacs` example shows `òàploiç...` in which `ploi` are right but see the others.. Instead the `cascadia-dos` example shows an empty box in place of an `à`

Thanks

**Comment by RWeigelt** [comment] 2019-09-19 19:58
Wow... lots of blank boxes:
![image](https://user-images.githubusercontent.com/1882836/65276538-38d26c80-db28-11e9-842a-c57c78845df0.png)

**Comment by cinnamon-msft** [comment] 2019-09-19 21:59
This is a duplicate of #33

**Closed by cinnamon-msft** 2019-09-19 21:59 UTC
