### ISSUE TITLE
Could you add the italics?

### ISSUE THREAD

**Issue by Someone-Of-Liu** [microsoft/cascadia-code#447] opened 2021-04-23 11:41 UTC
# Description of the new feature/enhancement (with images if possible)

 The Cascadia Code Font looks very nice. But when I use VScode with some theme. VScode will display comments and some keywords in italics. However, Cascadia Code doesn't have italics. So it looks doesn't very well. It's even a little ugly.😡 

# Proposed technical implementation details (optional)

 Could you add the italics? Just like Consolas Italics. It is very very pretty. Also, can you tell me when to add it? I am looking forward to it.😊

**Comment by aaronbell** [comment] 2021-04-23 13:32
This is a dupe of #63.

But yes, we are well aware of the need for an italic :). Hold tight!

**Closed by aaronbell** 2021-04-23 13:32 UTC
Labels: Issue-Feature
